--TABLA ALLOG
ALTER TABLE dbo.ALLOG ADD ALL_REMOTO BIT DEFAULT 0;
ALTER TABLE dbo.PARGEN ADD PAR_ACTIVO BIT DEFAULT 0;
ALTER TABLE dbo.PARGEN ADD PAR_CODIGOREMOTO TINYINT;
ALTER TABLE dbo.PARGEN ADD PAR_CARPETAFILES VARCHAR(100);
go
--UPDATE 
UPDATE dbo.PARGEN SET PAR_ACTIVO = 0
UPDATE dbo.PARGEN SET PAR_ACTIVO = 1 WHERE PAR_CODCIA IN('01','02')

UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 1 WHERE PAR_CODCIA='01'
UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 2 WHERE PAR_CODCIA='02'
UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 3 WHERE PAR_CODCIA='03'
UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 4 WHERE PAR_CODCIA='04'
UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 5 WHERE PAR_CODCIA='05'
UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 6 WHERE PAR_CODCIA='06'
UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 7 WHERE PAR_CODCIA='07'
UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 8 WHERE PAR_CODCIA='08'
UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 9 WHERE PAR_CODCIA='09'
UPDATE dbo.PARGEN SET PAR_CODIGOREMOTO = 30 WHERE PAR_CODCIA='30'
GO