IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_EMPRESAS_SYNC'
)
BEGIN
    DROP PROC [dbo].[USP_EMPRESAS_SYNC];
END;
GO
/*
USP_EMPRESAS_SYNC
*/
CREATE PROCEDURE [dbo].[USP_EMPRESAS_SYNC]
WITH ENCRYPTION
AS
SET NOCOUNT ON;


DECLARE @json NVARCHAR(MAX);
DECLARE @SQL VARCHAR(MAX);
DECLARE @SQL2 VARCHAR(MAX);

DECLARE @TBLRESPONSE TABLE(CODIGO INT,MENSAJE VARCHAR(300))

SET @json = '[' + STUFF((
    SELECT 
        ',{"idcia":"' + CAST(p.PAR_CODIGOREMOTO AS varchar(10)) + '","ruc":"' + p.PAR_RUC_EMP + '","empresa":"' + RTRIM(LTRIM(p.PAR_NOMBRE)) + ' - '+ RTRIM(LTRIM(p.PAR_NOMBRE_CORTO)) + '","direccion":"'+ RTRIM(LTRIM(COALESCE(p.PAR_DIR_EMP,''))) + '","carpeta":"' + COALESCE(p.PAR_CARPETAFILES,'') + '"}'
    FROM dbo.PARGEN p WHERE p.PAR_ACTIVO=  1 AND LEN(RTRIM(LTRIM(p.PAR_RUC_EMP)))<>0
    FOR XML PATH(''), TYPE
).value('.', 'NVARCHAR(MAX)'), 1, 1, '') + ']';


SET @SQL = 'call usp_empresa_insert(''' + @json + ''', @codigo, @mensaje);'

EXEC(@SQL) AT VENTAS;
--SELECT @SQL;

--OBTENIENDO RESPUESTA DEL SP DE MYSQL
SET @SQL2 = 'SELECT * FROM OPENQUERY(VENTAS,''select @codigo,@mensaje;'')';
		
		INSERT INTO @TBLRESPONSE
		(
			CODIGO,
			MENSAJE
		)
		EXEC(@SQL2)

		SELECT * FROM @TBLRESPONSE t


GO